### ISSUE TITLE
Your LTC6811 SPI interface pinout does not correspond with Vesc FW

### ISSUE THREAD

**Issue by Kabron287** [G-Pereira/greenmobi-bms#1]
Hi, there
I flash 1**2s7p\vesc_default.bin** from Vesc BMS github to Nucleo-F476 board and find it works.
But it doesn't work with LTC6811 board if I use SPI pinout from your schematic.
I rewired SPI according Ennoid BMS schematic and now it works with Vesc Tool SW. 

Correct pinout is:
PA4 - SS
PA5 - SCK
PA6 - MISO
PA7 - MOSI

**Comment by G-Pereira** [comment]
Hey @Kabron287 ! Thank you for your feedback. I have not crossed that board design when I did my research. That's exactly and I was aiming for on a second iteration of this project.
Do you think I can develop this project in a different direction than the Ennoid BMS which would be a good alternative? I don't have any reason to work on a board that will have the exact features of one that already is opensource.

**Comment by Kabron287** [comment]
> Do you think I can develop this project in a different direction than the Ennoid BMS which would be a good alternative?
Of course you can.
I guess it'll depend of the level of compatibility with Vesc FW if you do not wish to rewrite official FW or develop your own.

**Comment by G-Pereira** [comment]
I am aiming for complete compatibility not just because it would require me less work but most importantly so we can centralize efforts and contribute to the project and make it grow which would be better not only for me that I am using it but also for Benjamin, Trampa Boards and all other people using this ecosystem.

**Comment by Kabron287** [comment]
So, you have to change pinout, I guess.

**Comment by G-Pereira** [comment]
I am not sure because I am following the `hwconf/hw_rbat.h` and you are not using an MCU from the same STM32 line. I am using the STM32L476 at the moment.

**Comment by Kabron287** [comment]
Sorry, my board is NUCLEO-L476RG
I did not compile the code, just took from  /build_all

**Comment by G-Pereira** [comment]
Ah ok! That makes sense, you would need to compile with the pins I am using. But I will check which SPI pins I will choose. For now I am using the `hw_rabat.h` just to connect things as I go just to check the amount of pins I have available I will do a careful pin assignment once I am done with all sub circuits.

**Comment by G-Pereira** [comment]
I've close this for now because it isn't exactly an issue but I would like to continue the conversation on Discord, I've noticed you've joined us there!
