### ISSUE TITLE
MCP2562 alternative

### ISSUE THREAD

**Issue by Kabron287** [G-Pereira/greenmobi-bms#5]
In our design we use ADM3053BRWZ.
It has galvanic isolation with internal DC/DC converter.

**Comment by G-Pereira** [comment]
Hi @Kabron287, thank you for reviewing the design! It is very appreciated.

Our CAN bus will be used to establish data links between the BMS, motor controller and in the future our pedals, head unit and others. All those systems will be powered from the vehicle power bus so galvanic isolation would have no use here.

However, to protect external equipment (like a laptop) we should recommend that an isolated CAN transceiver is used to connect to the vehicle in those cases but only that adapter the user plugs into the vehicle requires isolation.
