### ISSUE TITLE
Add licence for contributions

### ISSUE THREAD

**Issue by A-damW** [G-Pereira/greenmobi-bms#9]
It is generally a good idea to add a licence.
The overall VESC project uses GPL-3.0, but you may want to do your own research and/or ask around on Discord from smarter people than I.

Nice write up for adding a licence:
[https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository](url)

**Comment by G-Pereira** [comment]
Thank you, I ended up going with GPL-3.0
